# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  name: Default

steps:
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'init'
    commandOptions: 'terraform init'
    backendServiceArm: 'Free Trial(568faec2-1839-4005-b760-e83e667c24d2)'
    backendAzureRmResourceGroupName: 'myproject'
    backendAzureRmStorageAccountName: 'projectnew1'
    backendAzureRmContainerName: 'container1'
    backendAzureRmKey: 'terraform.tf'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'plan'
    commandOptions: 'terraform plan'
    environmentServiceNameAzureRM: 'Free Trial(1)(568faec2-1839-4005-b760-e83e667c24d2)'
- task: TerraformTaskV4@4
  inputs:
    provider: 'azurerm'
    command: 'apply'
    commandOptions: 'terraform apply'
    environmentServiceNameAzureRM: 'Free Trial(2)(568faec2-1839-4005-b760-e83e667c24d2)'